// <auto-generated />
using System;
using BoxNovaSoftAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoxNovaSoftAPI.Migrations
{
    [DbContext(typeof(SebasSPContext))]
    [Migration("20241208235259_CreateNuevoDb")]
    partial class CreateNuevoDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoxNovaSoftAPI.Models.Carrito", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<float>("PrecioUnitario")
                        .HasColumnType("real");

                    b.Property<float>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("real")
                        .HasComputedColumnSql("[Cantidad] * [PrecioUnitario]");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdCliente");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("BoxNovaSoftAPI.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCProd"));

                    b.Property<bool>("EstadoCProd")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCProd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCProd");

                    b.ToTable("CategoriaProductos");
                });

            modelBuilder.Entity("BoxNovaSoftAPI.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CedulaCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DireccionCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneroCliente")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TelCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.HasIndex("CedulaCliente")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BoxNovaSoftAPI.Models.SubCategoriaProducto", b =>
                {
                    b.Property<int>("IdSubCProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubCProd"));

                    b.Property<bool>("EstadoCProd")
                        .HasColumnType("bit");

                    b.Property<int>("IdCProd")
                        .HasColumnType("int");

                    b.Property<string>("NombreCProd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdSubCProd");

                    b.HasIndex("IdCProd");

                    b.ToTable("SubCategoriaProductos");
                });

            modelBuilder.Entity("BoxNovaSoftAPI.Models.Carrito", b =>
                {
                    b.HasOne("BoxNovaSoftAPI.Models.Cliente", "Cliente")
                        .WithMany("Carritos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BoxNovaSoftAPI.Models.SubCategoriaProducto", b =>
                {
                    b.HasOne("BoxNovaSoftAPI.Models.CategoriaProducto", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("IdCProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BoxNovaSoftAPI.Models.CategoriaProducto", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("BoxNovaSoftAPI.Models.Cliente", b =>
                {
                    b.Navigation("Carritos");
                });
#pragma warning restore 612, 618
        }
    }
}
